[project]
name = "Music_Combiner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pytest>=8.3.5",
    "pytest-mock>=3.14.1",
    "tqdm>=4.67.1",
]
